<a href="https://colab.research.google.com/github/KitdelRosario/58013-Linear-Algebra/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A,"\n")

print(int(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]] 

-13
