<a href="https://colab.research.google.com/github/KitdelRosario/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Problem 1***

In [43]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

#A.)
DO = np.dot(A,B)
print("AB:")
print(DO)

#B.)
A = np.add(D,D)
print("D + D:")
print(A)

#C.)
M = np.multiply(2,C)
print("2C:")
print(M)

AB:
[[22 28]
 [49 64]]
D + D:
[[2 4]
 [6 8]]
2C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


***Problem 2***

In [29]:
import numpy as np

A = np.array([2,7,4])
B = np.array([3,9,8])

CP = [(A[1]*B[2]) - (A[2]*B[1]), (A[2]*B[0]) - (A[0]*B[2]), (A[0]*B[1]) - (A[1]*B[0])]

print(CP)

[20, -4, -3]
