<a href="https://colab.research.google.com/github/KitdelRosario/58013-Linear-Algebra/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Associative Property***

In [11]:
import numpy as np

A = np.array([[6, 6, 6],
                     [3, 7, 6],
                     [5, 7, 3]])

B = np.array([[1, 1, 2],
                     [3, 4, 1],
                     [6, 1, 8]])

C = np.array([[9, 2, 2],
                     [2, 3, 4],
                     [5, 6, 7]])

result1 = np.dot(np.dot(A, B), C)

result2 = np.dot(A, np.dot(B,C))

print("Matrix (AB)C:")
print(result1)

print("\nMatrix A(BC):")
print(result2)

Matrix (AB)C:
[[942 624 726]
 [919 597 695]
 [673 442 519]]

Matrix A(BC):
[[942 624 726]
 [919 597 695]
 [673 442 519]]


***Distributive property***

In [12]:
import numpy as np

A = np.array([[6, 6, 6],
                     [3, 7, 6],
                     [5, 7, 3]])

B = np.array([[1, 1, 2],
                     [3, 4, 1],
                     [6, 1, 8]])

C = np.array([[9, 2, 2],
                     [2, 3, 4],
                     [5, 6, 7]])

result1 = np.add(np.dot(A,B),np.dot(A,C))

result2 = np.dot(A, np.add(B,C))

print("Matrix (AB)C:")
print(result1)

print("\nMatrix A(BC):")
print(result2)

Matrix (AB)C:
[[156 102 144]
 [131 100 137]
 [118  85 100]]

Matrix A(BC):
[[156 102 144]
 [131 100 137]
 [118  85 100]]
