<a href="https://colab.research.google.com/github/KitdelRosario/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Associative Property***

In [10]:
import numpy as np

A = np.array([[6, 6, 6],
                     [3, 7, 6],
                     [5, 7, 3]])

B = np.array([[1, 1, 2],
                     [3, 4, 1],
                     [6, 1, 8]])

C = np.array([[9, 2, 2],
                     [2, 3, 4],
                     [5, 6, 7]])

result1 = np.dot(np.dot(A, B), C)

result2 = np.dot(A, np.dot(B,C))

print("Matrix (AB)C:")
print(result1)

print("\nMatrix A(BC):")
print(result2)

Matrix (AB)C:
[[942 624 726]
 [919 597 695]
 [673 442 519]]

Matrix A(BC):
[[942 624 726]
 [919 597 695]
 [673 442 519]]


***Distributive property***

In [8]:
import numpy as np

A = np.array([[6, 6, 6],
                     [3, 7, 6],
                     [5, 7, 3]])

B = np.array([[1, 1, 2],
                     [3, 4, 1],
                     [6, 1, 8]])

C = np.array([[9, 2, 2],
                     [2, 3, 4],
                     [5, 6, 7]])

result1 = np.add(np.dot(A ,B),np.dot(A,C))

result2 = np.dot(A, np.add(B,C))

print("Matrix (AB) + (AC):")
print(result1)

print("\nMatrix A + (BC):")
print(result2)

Matrix (AB) + (AC):
[[156 102 144]
 [131 100 137]
 [118  85 100]]

Matrix A + (BC):
[[156 102 144]
 [131 100 137]
 [118  85 100]]


***Closure Property***

In [2]:
import numpy as np

A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

C = np.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 18, 19]])

AB = np.dot(A, B)
BC = np.dot(B, C)

print("Matrix A * Matrix B:")
print(AB)

print("\nMatrix B * Matrix C:")
print(BC)

Matrix A * Matrix B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix B * Matrix C:
[[330 354 378]
 [204 219 234]
 [ 78  84  90]]


***Identity Property***

In [5]:
import numpy as np


A = np.array([[6, 5, 3],
                     [3, 2, 1],
                     [9, 6, 9]])


identity = np.array([[1, 0, 0],
                            [0, 1, 0],
                            [0, 0, 1]])

result = np.dot(A, identity)

print("Matrix A:")
print(A)

print("\nIdentity Matrix:")
print(identity)

print("\nMatrix A * Identity Matrix:")
print(result)

Matrix A:
[[6 5 3]
 [3 2 1]
 [9 6 9]]

Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Matrix A * Identity Matrix:
[[6 5 3]
 [3 2 1]
 [9 6 9]]


***Zero Property***

In [7]:
import numpy as np


A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


zero = np.zeros((3, 3))

result = np.dot(A, zero)

print("Matrix A:")
print(A)

print("\nZero Matrix:")
print(zero)

print("\nMatrix A * Zero Matrix:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix A * Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


***Scalar Property***

In [9]:
import numpy as np


matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


scalar = 2

result = scalar * matrix_A

print("Matrix A:")
print(matrix_A)

print("\nScalar (Multiplier):", scalar)

print("\nScalar Multiplication of Matrix A:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Scalar (Multiplier): 2

Scalar Multiplication of Matrix A:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
