<a href="https://colab.research.google.com/github/KitdelRosario/58013-Linear-Algebra/blob/main/Vector%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Vector, Spaces and Operations***

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ',A)
print('Vector B is ',B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


***Shape of the Matrix***

In [19]:
###Checking Shapes
#Shapes tells us how many rows and columns are there

import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1) + np.shape(ball2)
print(ball)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [6]:

import numpy as np

ball1 = np.array([[1],[2],[3]])
print(ball1)


[[1]
 [2]
 [3]]


***Addition***

In [42]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

R = np.add(A,B)
print(R)

[ 6 -2]


***Subtraction***

In [41]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

R1 = np.subtract(A,B)
print(R1)

R2 = np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


***Scalar Product***

In [35]:
S = np.array([2])
V = S*A
print(V)

[[8]
 [6]]


***Dot Product***

In [49]:
import numpy as np
A = np.array([4,3])
B = np.array([[2],[-5]])

R2 = np.multiply(A,B)
print(R2)

[[  8   6]
 [-20 -15]]


***Matrix Property***

In [70]:
#property of  matrix
#Identity matrix
c = np.eye(3,3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
#Zero Matrix

d=np.zeros([5,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
#null Matrix

e = np.full((3,3),7)
print(e)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [67]:
#Transpose Matrix
f = np.transpose(A)
print(f)

[4 3]
